### ISSUE TITLE
Debug google analytics API access

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/dlme#522]
Confirmed that we are capturing google analytics on page views, however the key file used for API access appears to timeout after a short period (perhaps an hour or less), so display of analytics in the UI is not functioning.

**Comment by cbeer** [comment]
I don't see any indication that Google Analytics API access was ever set up in the AWS stuff. It looks like there's at least two difference service accounts with appropriate access (`dlme-analytics-reader@...` + `dlme-network@...`), but without a credentials file over in AWS land.

@aaron-collier, do you know anything about where/how the credentials were generated, or was that all @waynegraham ?

**Comment by waynegraham** [comment]
I had initially set up the accounts, but there were some issues that @aaron-collier resolved with the `dlme-analytics-reader@...` and `dlme-network@...` analytics accounts. According to my emails, there was also an OAuth account that needed to be set up. I took a quick look and I'm not seeing a Google project for DLME though. Maybe the OAuth user got blasted? I can create a new project and add appropriate users (or let you all do it if it's easier).

**Comment by mejackreed** [comment]
@waynegraham I think that makes sense to create a new project and add the appropriate service accounts needed for access to the Google Analytics API. If you go ahead and create that, could you also create the .p12 file and provide that to us securely. 

https://developers.google.com/analytics/devguides/reporting/core/v4/authorization

**Comment by waynegraham** [comment]
I sent an email for follow up on this with the generated key.

**Comment by mejackreed** [comment]
@aaron-collier we resolved the N/A issue upstream in spotlight with https://github.com/projectblacklight/spotlight/pull/2312.

However, we are still seeing the issue where after the deploy everything works fine. But a few hour(s) later, it doesn't work anymore. https://app.honeybadger.io/projects/53082/faults/57672876

Can we circle back to look at how fargate/Docker is not keeping those configs/ENV vars?
